### PR TITLE
testlogger: add lock around output to avoid data race in writing to output

### PR DESCRIPTION
**Pull request by acgreek**
```
WARNING: DATA RACE
Write at 0x00c0002dd940 by goroutine 9:
  bytes.(*Buffer).Write()
      /usr/local/go/src/bytes/buffer.go:169 +0x44
  github.com/secureworks/logger/testlogger.(*Entry).Send()
      /go/pkg/mod/github.com/secureworks/logger/testlogger@v1.0.1/testlogger.go:288 +0x2a9
  github.com/secureworks/logger/testlogger.(*Entry).Msg()
      /go/pkg/mod/github.com/secureworks/logger/testlogger@v1.0.1/testlogger.go:270 +0x94
```

### CODE REVIEW

**Review by acgreek — COMMENTED** [review]
revert module path

**Review by iaburton — CHANGES_REQUESTED** [review]
I thought there was an issue/bug for this actually because I've run into the same problem of this testlogger not being concurrency safe :slightly_smiling_face: thanks for making these changes.

**Comment by iaburton** [comment]
_As_ a change this looks fine to me, though it is a _breaking_ one now. Given its in the 'testlogger' though I'm not sure how strict we care to be about it from an API/SDK perspective.

@hews thoughts?

**Review by iaburton — APPROVED** [review]
Waiting on another code owner before merge on this one. Approved though.

**Review by hews — APPROVED** [review]
Yeah, I think the testlogger came out half-baked anyway, this is a great change and I think it's fine for it to break (ideally it's only being used in tests anyway).

However, we need signed commits: please rebase these commits and sign, or close this and resubmit.

**Comment by hews** [comment]
Closed in favor of #18

**Pull request closed without merging**
